development:
  adapter: postgresql
  database: initials_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: initials_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: initials_production
  pool: 5
  timeout: 5000
