# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_INITIALS_LIST_ID"] %>
  secret_key_base: 14b07f340fe8b315c037270cc3c0d9708df70f334a377ca9cbd771f1d76517d5dedc9145bd4e977c1b51cda9d8c56f02a1555e5931c56c82252ad661357dfe04

test:
  secret_key_base: 3aa0236cf243a8428fc30ecc7b10f8897c5d7696e5e88ef53104f07f28550cb63beb8b925329e8ceba7978b8c368a3dd85d765fe667ef20603f83ebcb462f84a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_INITIALS_LIST_ID"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
